### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by Xyrion** [mihirsoni/odfe-monitor-cli#3]
Running: odfe-monitor-cli -e https://localhost:9200 -p "password" sync --destinations

And error: panic: interface conversion: interface {} is nil, not string

I looked at destination.go and ran the {"size": 10000, "query":{ "bool": {"must": { "exists": { "field" : "destination" }}}}}, looking at the results I dont see any reference of Interface.

**Comment by mihirsoni** [comment]
HI @Xyrion  Thank you for reporting this issue. This has been fixed and released under new version. You could install latest version and the issue shouldn't persist. 

Let me know if you still face any other issue.
