### ISSUE TITLE
Does destinations able to fully backup ?

### ISSUE THREAD

**Issue by sendme365** [mihirsoni/odfe-monitor-cli#5]
The sync --destinations looks like key:value for destinations name and some hash key not full destinations information.

How can I backup and restore destinations ? Thanks

**Comment by mihirsoni** [comment]
@sendme365 Thanks for reporting an issue. This feature is currently not there but would be good to have. I'll put this as part of backlog and work on this. Feel free to contribute back and have PR for the same.
